version: '3'

services:
  test:
    container_name: lumen-directory-test
    tty: true
    build: ./docker/api
    environment: 
      - APP_ENV=testing
      # - PHPUNIT_PARAMS=--debug
    volumes:
      - ./api:/src