version: '3'

services:
  web:
    container_name: lumen-directory
    tty: true
    build: .
    env_file: .env
    volumes:
      - .:/src
    ports:
      - "3000:8080"
    links:
      - database

  database:
    container_name: lumen-database
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=lumen
      - MYSQL_USER=lumen
      - MYSQL_PASSWORD=123
    ports:
      - "3001:3306"
    volumes:
      - ./.docker/_data/mysql:/var/lib/mysql
      - ./.docker/_data/logs:/var/logs/mysql