version: '3'

services:
  api:
    container_name: lumen-api
    tty: true
    build: ./docker/api
    env_file: ./api/.env
    volumes:
      - ./api:/src
    ports:
      - "3001:8080"
    links:
      - database

  database:
    container_name: lumen-database
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=lumen
      - MYSQL_USER=lumen
      - MYSQL_PASSWORD=123
    ports:
      - "3002:3306"
    volumes:
      - ./.data/mysql:/var/lib/mysql
      - ./.data/logs:/var/logs/mysql